version: '2'
services:
  web:
    build: 
      context: ./webapp
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    
    volumes:
      - ./webapp:/app
    
    command: python main.py
    